apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: web-dev-
namespace: web-dev
resources:
  - ../../base
patches:
  - path: patch-deploy.yaml
images:
  - name: nhutlm1/react-nginx
    newName: nhutlm1/react-nginx
    newTag: 1.0.2
