apiVersion: v1
kind: Service
metadata:
  name: react-nginx
  labels:
    app: react-nginx
spec:
  selector:
    app: react-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
